accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aphoton"]
  - name: bob
    coins: ["5000000000000aphoton"]
  - name: faucet
    coins: ["100000000000000000000000aphoton"]
  - address: ethm1kch0sdjr5tuvjh0h3a55c6l5sr6m0phjda3j76
    coins: ["100000000uatom", "100000000000000000000aphoton"]
validator:
  name: alice
  staked: "10000000000000aphoton"
faucet:
  port: 4500
  name: "faucet"
  coins: ["1000000000000aphoton"]
  coins_max: ["100000000aphoton"]
build:
  binary: "ethermintd"
init:
  home: "$HOME/.ethermintd"
  app:
    log_level: debug
    api:
      enable: true
    json-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "ethermint_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "aphoton"
    mint:
      params:
        mint_denom: "aphoton"
    crisis:
      constant_fee:
        denom: "aphoton"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aphoton"
    evm:
      params:
        evm_denom: "aphoton"
    feemarket:
      params:
        base_fee: "50000000000"
        base_fee_change_denominator: 300
        elasticity_multiplier: 4
        enable_height: "0"
        min_gas_multiplier: "0.5"
        min_gas_price: "50000000000.0"
        no_base_fee: false
        legacy_base_fee: "1000000000"
        legacy_min_gas_price: "1000000000.0"